import java.util.*;
import java.util.concurrent.TimeUnit;
public class run
{
  private String choice;
  private String link = "https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2FDARK-COBRA%2FDARKCOBRA&template=https%3A%2F%2Fgithub.com%2FDARK-COBRA%2FDARKCOBRA";//Deployment Link
  private String trb_bot = "https://t.me/vTelegraphBot";//Telegraph Bot link
  private String scrap_bot = "https://t.me/UseTGXBot";
  private String dc_api_bot = "https://t.me/DC_API_HASH_BOT";
  private String repl = "https://darkcobra1.crazycreatorr.repl.run";
  private String botf = "https://t.me/FAthrBOT";
  private String Channel = "https://t.me/Dark_cobra_support";
  private String Group = "https://t.me/Dark_cobra_support_group";
  Scanner sc = new Scanner(System.in);
  public void run() throws InterruptedException
  {
    System.out.println("Hey lets begin!");
    TimeUnit.SECONDS.sleep(2);
    System.out.println("What Do you want me to Explain ");
    TimeUnit.SECONDS.sleep(2);
    System.out.println("Enter Deploy ");
    TimeUnit.SECONDS.sleep(1);
    System.out.println("To start The Tutorial");
    TimeUnit.SECONDS.sleep(1);
    choice = sc.nextLine();
    if(choice.equals("Deploy")||choice.equals("deploy")||choice.equals("DEPLOY"))
    {
      System.out.println("OK! ");
      TimeUnit.SECONDS.sleep(1);
      System.out.println("So, Deployment is a process by which you can Access the Userbot Service!");
      TimeUnit.SECONDS.sleep(4);
      System.out.print("You ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Can ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Deploy ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Your ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Own ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Userbot ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("By ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("this ");
      TimeUnit.SECONDS.sleep(1);
      System.out.println("Link ");
      TimeUnit.SECONDS.sleep(1);
      System.out.println(link);
      TimeUnit.SECONDS.sleep(8);
      System.out.print("So, ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Lets ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Talk ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("about ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("How ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("to ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Fill ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Vars ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("On ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("the ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("Deployment ");
      TimeUnit.SECONDS.sleep(1);
      System.out.println("Page ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("So, Lets talk about the mandatory vars which will be needed to Deploy your 'APP'");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("So the first is App name");
      TimeUnit.SECONDS.sleep(1);
      System.out.println("'App-name' is the name to your app it should be unique and available if it shows the Error try a new name name again");
      TimeUnit.SECONDS.sleep(4);
      System.out.print("Then, ");
      TimeUnit.SECONDS.sleep(1);
      System.out.print("its ");
      TimeUnit.SECONDS.sleep(1);
      System.out.println("Alive msg ");
      TimeUnit.SECONDS.sleep(3);
      System.out.println("So, In Alive msg u ca fill any custom Alive msg like 'I am alive' or whatever you want ");
      TimeUnit.SECONDS.sleep(5);
      System.out.println("Then, it's Alive Photto It is Auto-Filled but rest you can change and fill your own Alive Photto by just going to "+trb_bot+" bot and sending the photo i file format you will get a link fill it in the Alive Photto Menu");
      TimeUnit.SECONDS.sleep(10);
      System.out.println("Then, there are the most important Vars ");
      TimeUnit.SECONDS.sleep(1);
      System.out.println("API HASH ");
      TimeUnit.SECONDS.sleep(1);
      System.out.println("You can get this by "+dc_api_bot+" or "+scrap_bot+" Just Enter your Number in International Format");
      TimeUnit.SECONDS.sleep(6);
      System.out.println("ex: India(+91) ");
      TimeUnit.SECONDS.sleep(1);
      System.out.println("After that you will get a Confirmation code on Telegram Copy it and Paste it there in the Bot");
      TimeUnit.SECONDS.sleep(5);
      System.out.println("Fill the API Hash in the ID in the Vars ");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Then, its Emojji to Display in help ");
      TimeUnit.SECONDS.sleep(1);
      System.out.println("Fill any Random Emoji there ");
      TimeUnit.SECONDS.sleep(3);
      System.out.println("Then, its HEROKU_API_KEY fill the API ID here as u Fill in the Above Var ");
      TimeUnit.SECONDS.sleep(3);
      System.out.println("Then, In HEROKU_APP_NAME you can fill any Random name to your bot such as 'DARK_COBRA'");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("In, NO_OF_BUTTONS_DISPLAYED_IN_H_ME_CMD Fill 5");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("In, NO_OF_COLUMS_DISPLAYED_IN_H_ME_CMD Fill 2");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Then, Make a Channel in Telegram and Add Rose Bot there then type /id to get ur id the fill it in the PLUGIN_CHANNEL ");
      TimeUnit.SECONDS.sleep(3);
      System.out.println("PM_LOGGR_BOT_API_ID Same id Filled in PLUGIN_CHANNEL ");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("In, PMPERMIT_PIC Paste the link of the pic Filled in ALIVE_PHOTTO ");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Then, PRIVATE_GROUP_BOT_API_ID Fill Same as PLUGIN_CHANNEL");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Then, PRIVATE_GROUP_ID Fill Same as PLUGIN_CHANNEL");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Then, STRING_SESSION Make it By Using the repl "+repl);
      TimeUnit.SECONDS.sleep(2);
      System.out.println("At Last make a Bot at BotFather "+botf+" And then Revoke its API-TOKEN and fill it in TG_BOT_TOKEN_BF_HER");
      TimeUnit.SECONDS.sleep(3);
      System.out.println("Then, your Bot name with '@' sign i Front Fill it in TG_BOT_USER_NAME_BF_HER ");
      TimeUnit.SECONDS.sleep(3);
      System.out.println("Then, Click on Deploy Button");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("It Will Take Some Time");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("After that Go to Mage Apps Option ");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Then, Go to Configure-Dynos and Turn it On ");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Then, Go to View logs and wait it will take a few minutes ");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("After the Process is Complete ");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Write .alive in any of the chat's ");
      TimeUnit.SECONDS.sleep(3);
      System.out.println("Congraculations! You Have make your own DARK-COBRA Userbot");
      TimeUnit.SECONDS.sleep(4);
      System.out.println("To Test Some Commands Type .help");
      TimeUnit.SECONDS.sleep(3);
      System.out.println("For Any Kind Of help ");
      TimeUnit.SECONDS.sleep(3);
      System.out.println("Join The Support Channel "+Channel);
      TimeUnit.SECONDS.sleep(4);
      System.out.println("Join The Support Group "+Group);
      TimeUnit.SECONDS.sleep(4);
      System.out.println("So, This was the AI Tutorial");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Hope you Enjoy that");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Thank's For Coming!");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("In the end a last quote for Atul");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Are Pagle ye kyu Sochta ha tune mujhe kho diya abe Salle khoya kya Tune to mujhe Jeet Liya ");
      TimeUnit.SECONDS.sleep(5);
      System.out.println("Hmm.. Thoda Gussa ho sakta hu Par tujhe Bhul jau Aisa kabhi nhi ho sakta ");
      TimeUnit.SECONDS.sleep(5);
      System.out.println("At then end bas itna Bolunga Kabhi bhulna mat mereko.....");
      TimeUnit.SECONDS.sleep(5);
      System.out.println("Chiyu is Disconnected Due to Some Work!");
      TimeUnit.SECONDS.sleep(2);
      System.out.println("Bbye!!");
      TimeUnit.SECONDS.sleep(2);
      System.exit(0);
    }
  }
  public static void main(String args[]) throws InterruptedException
  {
    run start = new run();
    start.run();
  }
}
